repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.2
      hooks:
          - id: aoc-tiles
            args:
                - --auto-add-tiles-to-git=amend
                - --contrast-improvement-type=dark
                - --create-all-days=True
                - --count-as-solved-when=on_leaderboard
                - --overwrite-year=2024